### ISSUE TITLE
Error downloading dependencies

### ISSUE THREAD

**Issue by rsalz** [sheynkman-lab/Long-Read-Proteogenomics#164]
Followed the instructions creating a fresh conda environment and downloading/specifying nextflow version.
When I try to run the nextflow pipeline main.nf all the dependencies start to download and then it runs into this error:

```
CAPSULE: Downloading dependency com.amazonaws:aws-java-sdk-ecs:jar:1.11.542
CAPSULE: Downloading dependency org.eclipse.jgit:org.eclipse.jgit:jar:5.2.1.201812262042-r
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0
CAPSULE: Downloading dependency commons-codec:commons-codec:jar:1.10
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at nextflow.cli.Launcher.$getStaticMetaClass(Launcher.groovy)
        at nextflow.cli.Launcher.<init>(Launcher.groovy)
        at nextflow.cli.Launcher.main(Launcher.groovy:641)
```

Any ideas on how i can fix this?

**Comment by Sktbanerjee1** [comment]
Thank you so much for opening this issue; I think it's a java installation-related problem which is causing this. Please reinstall the Java Runtime Environment (latest) and follow this [nextflow hello world](https://www.nextflow.io/docs/latest/getstarted.html), making sure you are able to run a barebone Nextflow pipeline before reattempting the LRP run. I will also request you to look into this kindly [Conda Nextflow documentation ](https://www.nextflow.io/docs/latest/conda.html).

If this issue continues to persist, please consider using the [docker images](https://hub.docker.com/search?q=gsheynkman).
